### ISSUE TITLE
Auto-restart not working

### ISSUE THREAD

**Issue by zedtux** [Douane/douane-configurator#10]
When i restart or re-log into my account after having enabled the auto restart, the firewall wasn't active and has the 'D-Bus service org.zedroot.Douance not found' error.

**Comment by unidesign** [comment]
For me it is not possible to autostart `douane` firewall (tested using `douane-configurator` with and without `sudo`). Can you pls explain what is needed to autostart it manually?

**Comment by zedtux** [comment]
@unidesign what's Mint using ? Init V or systemd ?

**Comment by unidesign** [comment]
I'm using 17.1 afaik `systemd` is not standard.

**Comment by zedtux** [comment]
Alright, thank you I will have a look

**Comment by hagaram** [comment]
Hello, I'm following up on our recent conversation:
Douane module is not loaded after reboot, but Im able to load it manually:
sudo insmod /lib/modules/4.4.0-42-generic/kernel/net/douane/douane.ko

and then start it:
systemctl daemon-reload
sudo service douane start

 Im using Mint 18 with systemd, kernel 4.4.0-42. What can I try to help you "debug" this issue?

**Comment by zedtux** [comment]
According to [this article](http://www.cyberciti.biz/faq/linux-how-to-load-a-kernel-module-automatically-at-boot-time/), Douane's module should be inserted in the `/etc/modules.conf` file in order to be automatically loaded on boot.

Can you please check this file (honestly I don't remember, for now, how I have built the autoload feature)

**Comment by hagaram** [comment]
Just for the sake of comprehensiveness the structure in Mint 18 looks like this:

/etc/modules
/etc/modules-load.d/modules.conf -> ../modules
But the file is empty:
```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
```

 I'll try to add douane module to this file and let you know.

**Comment by hagaram** [comment]
So after adding "douane"
to **/etc/modules**

And "sudo service douane start"
to **/etc/rc.local**

Douane start on startup as it should.

**Comment by zedtux** [comment]
Well, that's nice, it means that the Douane project needs to be updated in order update that file.

**Comment by intika** [comment]
there is a lot of duplicated bug... 
is this bug still here on last version ?
can someone try please

**Comment by zedtux** [comment]
@intika please link duplicated issues so that I can clean them.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-configurator/issues/10).
