### ISSUE TITLE
No icons generated after installation

### ISSUE THREAD

**Issue by zedtux** [Douane/douane-configurator#23]
@unidesign has opened the issue Douane/Douane#43:

> After compilation and installation the manual page implifies that icons/shortcuts are now generated,
> but that's not true at least for linux mint. Here is explained how to shortcut an application for linux systems: http://www.sysads.co.uk/2014/04/install-latest-eclipse-ide-ubuntu-14-04-13-10/

**Comment by zedtux** [comment]
I confirm that after installing Douane, the douane configurator is no more available as an application in the system.

**Comment by intika** [comment]
i fixed the system app, now need to add the icon ill do it later
