### ISSUE TITLE
Add package gtk+3.0 to dependencies

### ISSUE THREAD

**Issue by wiserweb** [Douane/douane-configurator#24]
Followed all the steps in the install guide but couldn't get the configurator dialog.

I was able to get Douane working by installing latest gtk+ package.

Debian/Ubuntu/Mint
sudo apt-get install gtk+3.0

Seems gtk+3.0 should be included in dependencies.

I updated the wiki (https://github.com/Douane/Douane/wiki/Dependencies) and this ticket is to request that gtk+3.0 also be included in the readme.

**Comment by zedtux** [comment]
Thank you @wiserweb for this.
