### ISSUE TITLE
sendmsg: Connection Refused

### ISSUE THREAD

**Issue by zedtux** [Douane/douane-configurator#25]
@cmalkus said from Douane/Douane#59:

> I get the following error in my log file when I turn the configurator on. I also have a red notification next to the switch that says D-bus service org.zedroot.Douane not found on mouseover

> 30/07/2016 16:02:18 INFO: Loaded 136 Freedesktop desktop files
> 30/07/2016 16:02:18 INFO: Loaded 0 rules
> 30/07/2016 16:02:18 ERROR: Error while calling sendmsg: Connection refused
> 30/07/2016 16:02:18 ERROR: Unable to send message

> I am running Ubuntu 16.04 and I installed via the instructions found here https://github.com/Douane/Douane/wiki/Compilation

> I also had to manually create the rules file and add an empty object {}

**Comment by zedtux** [comment]
Hello @cmalkus and thank you for using Douane :-)

So the message `D-bus service org.zedroot.Douane not found` means that the daemon is not running.
Can you please have a look at the `/var/log/douane.log` file and post its content so that I can help you?

**Comment by cmalkus** [comment]
The relevant part of the log in in the original issue. There are a few instances of `INFO: The log file is /var/log/douane.log` but nothing else as far as errors. I can give you the entire log if you like

**Comment by zedtux** [comment]
You can start the daemon process using the `-D` flag in order to enable the debug mode and log more things.

**Comment by zedtux** [comment]
Have at https://github.com/Douane/Douane/wiki/Debugging in case you need it.

**Comment by cmalkus** [comment]
With the debugger on I get this:

'31/07/2016 16:07:01 | daemon |  INFO | [freedesktop/desktop_files.cpp::DesktopFiles:7]: Loaded 147 Freedesktop desktop files'
'31/07/2016 16:07:01 | daemon | DEBUG | [main.cpp::Main:259]: Initializing RulesManager'
'31/07/2016 16:07:01 | daemon | DEBUG | [rules_manager.cpp::RulesManager:126]: RulesManager::load_rules_from_file...''
'31/07/2016 16:07:01 | daemon | DEBUG | [tools.cpp::Tools:49]: Douane root path is /opt/douane'
'31/07/2016 16:07:01 | daemon |  INFO | [rules_manager.cpp::RulesManager:156]: Loaded 0 rules'
'31/07/2016 16:07:01 | daemon | DEBUG | [rules_manager.cpp::RulesManager:7]: RulesManager initialization done'
'31/07/2016 16:07:01 | daemon | DEBUG | [main.cpp::Main:262]: Initializing ProcessesManager'
'31/07/2016 16:07:01 | daemon | DEBUG | [main.cpp::Main:267]: Initializing DBusServer'
'31/07/2016 16:07:01 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:8]: Initializing D-Bus server'
'31/07/2016 16:07:01 | daemon | DEBUG | [main.cpp::Main:277]: Connecting objects'
'31/07/2016 16:07:01 | daemon | DEBUG | [main.cpp::Main:315]: Starting to listen to LKM. Daemon is alive!''
'31/07/2016 16:07:01 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:163]: NetlinkListener::build_message...'
'31/07/2016 16:07:01 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:155]: NetlinkListener is sending the hand check'
'31/07/2016 16:07:01 | daemon | ERROR | [netlink_listener.cpp::NetlinkListener:196]: Error while calling sendmsg: Connection refused'
'31/07/2016 16:07:01 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:25]: Initializing D-Bus server...'
'31/07/2016 16:07:01 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:13]: Shutting down D-Bus server..'
'31/07/2016 16:07:01 | daemon | ERROR | [main.cpp::Main:323]: Unable to send message'
'31/07/2016 16:07:01 | daemon | DEBUG | [socket.cpp::Socket:27]: Closing socket 3'
'31/07/2016 16:07:01 | daemon | DEBUG | [socket.cpp::Socket:30]: Socket closed'

Also in the terminal I get this message `Segmentation fault (core dumped)'

**Comment by zedtux** [comment]
@cmalkus can you please post the output of the following command:

```
$ lsb_release -a
```

**Comment by cmalkus** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by zedtux** [comment]
What's the output of the following command:

```
$ lsmod | grep douane | wc -l
```

**Comment by cmalkus** [comment]
`0`

**Comment by zedtux** [comment]
This means the `douane-dkms` is not loaded.

Try again to compile it and to install it. The previous command should return `1` in order to get ride of this error.

**Comment by hagaram** [comment]
Ok, bassicaly I have the same problem. Ive read whole thread (didnt try to debbug etc. just went straight to "lsmod | grep douane | wc -l"), Ive rebuilded DKMS module and it was working fine. But just like previously, after OS restart Douane stops working. Any help will be greatly appreciated

**Comment by zedtux** [comment]
As far as I can understand your issue @hagaram, it sounds more like a Douane-not-starting-automatically issue, right?
This issue is known and described in the issue Douane/douane-configurator#10

**Comment by hagaram** [comment]
Well module is not loaded after reboot, but Im able to load it manually:
sudo insmod /lib/modules/4.4.0-42-generic/kernel/net/douane/douane.ko

and then start it:
systemctl daemon-reload
sudo service douane start

So I dont know which issue is be more suitable. Im using Mint 18 with systemd.

**Comment by zedtux** [comment]
> So I dont know which issue is be more suitable.

Definitely the Douane/douane-configurator#10

Especially that people on this issue are using the same distrib than you.
