### ISSUE TITLE
PyGIWarning: Gtk was imported without specifying a version first.

### ISSUE THREAD

**Issue by zedtux** [Douane/douane-configurator#26]
When launching `douane-configurator` from the terminal we can see  the following message:

```
/usr/local/bin/douane-configurator:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, Gdk
```

**Comment by intika** [comment]
fixed when on my first compiled version... i forget about it but here is the code i'll pull request
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib, Gdk

**Comment by intika** [comment]
done https://github.com/Douane/douane-configurator/pull/30
